#include "game.h"

#include <stdio.h>
#include <stdlib.h>
#include "gba.h"
#include "images/goku.h"
#include "images/gokuUp.h"
//#include "images/gokuDown.h"
#include "images/startscreen.h"
#include "images/gameover.h"
#include "images/horizon.h"
#include "images/background.h"
#include "images/buu1.h"
#include "images/buu2.h"
#include "images/genkidama.h"



/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app.
typedef enum {
    START,
    START_NO_DRAW,
    DIALOGUE_1,
    DIALOGUE_2,
    DIALOGUE_END_1,
    DIALOGUE_END_2,
    PLAY,
    END_1,
    END_2
} GBAState;

//int calcStringWidth(char *string) {
//    return (int) ((strlen(string) - 1) * 6);
//}

SonGoku myGoku = {125, 1, 1, 1, goku};
Buu myBuu = {180, 134, 19, 10, buu2};
GenkiDama spiritbomb = {HEIGHT/2 +25,WIDTH/2 - 80,GENKIDAMA_HEIGHT,GENKIDAMA_WIDTH,genkidama};
volatile int points = 0;
volatile int speed = 2;
int detectCollision(void);
void gokuMove(char d);
void delay(int n);


int main(void) {
                    /* TODO: */
    // Manipulate REG_DISPCNT here to set Mode 3. //
    REG_DISPCNT = MODE3 | BG2_ENABLE;
    // Save current and previous state of button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    // Load initial game state
    GBAState state = START;
    int frameCount = 0;

    speed = 2;
    points = 0;
    myGoku.row = HEIGHT/2 +30;
    myGoku.col = WIDTH/2 - 80;
    myBuu.col = 180;
    myBuu.row = 35;
    myBuu.image = buu2;
    myBuu.width = 52;
    myBuu.height = 52;
    spiritbomb.row = HEIGHT/2 - 10;
    spiritbomb.col = WIDTH/2 - 75;
    int rd = 1;
  //  int cd = 1;;

    while (1) {
        frameCount++;
        currentButtons = BUTTONS; // Load the current state of the buttons

        if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
        	state = START; // If at any time they press Backspace, go back to beginning
            speed = 2;
            points = 0;
            myGoku.row = HEIGHT/2 +30;
            myGoku.col = WIDTH/2 - 80;
            myBuu.row = 35;
            myBuu.col = 180;
            myBuu.image = buu2;
            myBuu.width = 52;
            myBuu.height = 52;
            spiritbomb.row = HEIGHT/2 - 10;
            spiritbomb.col = WIDTH/2 - 75;

        }

                    /* TODO: */
        // Manipulate the state machine below as needed //
        // NOTE: Call waitForVBlank() before you draw

        switch(state) {
            case START:
                waitForVBlank();
                drawFullScreenImageDMA(startscreen);
                drawString(HEIGHT/2 - 10 + 40, WIDTH/2 - 40,  "DBZ: Buu's Fury", RED);
                drawString(HEIGHT/2 + 40, WIDTH/2 - 40,  "Press Up to play", RED);
                state = START_NO_DRAW;
                break;
            case START_NO_DRAW:

                if (KEY_JUST_PRESSED(BUTTON_UP, previousButtons, currentButtons)) {
                    waitForVBlank();
                    fillScreenDMA(BLACK); //background
                    drawImageDMA(myGoku.row,myGoku.col ,52, 52, goku);
                    drawRectDMA(30, 0, 240, 1, WHITE); //bar on top
                    drawImageDMA(myBuu.row, myBuu.col, myBuu.width, myBuu.height, myBuu.image);
                    drawString(20, 30, "THE LAST BATTLE", WHITE);
                    drawImageDMA(spiritbomb.row,spiritbomb.col ,spiritbomb.width, spiritbomb.height, spiritbomb.image);
                    delay(1);
                    state = DIALOGUE_1;

                }
                break;
            case DIALOGUE_1:
            waitForVBlank();
            drawString(myGoku.row,myGoku.col + 50,"I have no more energy!", WHITE);
            delay(1);


            //drawString(a,a,"Help me out!")


            if (KEY_JUST_PRESSED(BUTTON_UP, previousButtons, currentButtons)) {
                waitForVBlank();
                drawRectDMA(myGoku.row,myGoku.col + 50,135, 100, BLACK);
                state = DIALOGUE_2;
            }


            break;

            case DIALOGUE_2:
            waitForVBlank();
            drawString(myGoku.row,myGoku.col + 50,"Hey you! help me out!", WHITE);

            drawRectDMA(18, 30, 240, 10,BLACK );
            drawString(20, 30, "CONTROL THE BALL!", WHITE);

            if (KEY_JUST_PRESSED(BUTTON_UP, previousButtons, currentButtons)) {
                waitForVBlank();
                drawRectDMA(myGoku.row,myGoku.col + 50,140, 100, BLACK);
                state = PLAY;
            }
            break;

            case PLAY:
                    waitForVBlank();
                    if (KEY_DOWN(BUTTON_UP, BUTTONS))
                    spiritbomb.row = spiritbomb.row - 1;
                    drawRectDMA(spiritbomb.row,spiritbomb.col ,spiritbomb.width, 1, BLACK);

                    if (KEY_DOWN(BUTTON_DOWN, BUTTONS))
                    spiritbomb.row = spiritbomb.row + 1;
                    drawRectDMA(spiritbomb.row,spiritbomb.col ,spiritbomb.width, 1, BLACK);

                    if (KEY_DOWN(BUTTON_RIGHT, BUTTONS))
                    spiritbomb.col = spiritbomb.col + 1;
                    drawRectDMA(spiritbomb.row,spiritbomb.col ,1, spiritbomb.height, BLACK);

                    if (KEY_DOWN(BUTTON_LEFT, BUTTONS))
                    spiritbomb.col = spiritbomb.col - 1;
                    drawRectDMA(spiritbomb.row,spiritbomb.col ,1, spiritbomb.height, BLACK);



                    if (spiritbomb.col < 0 ) {
                      spiritbomb.col = 0;
                    }

                    if (spiritbomb.col > WIDTH - BUU2_WIDTH) {
                      spiritbomb.col = WIDTH - BUU2_WIDTH;
                      state = DIALOGUE_END_1;
                      break;
                    }


                    if(spiritbomb.row < 35) {
                      spiritbomb.row = 35;
                      rd = -rd;
                    }
                    if(spiritbomb.row > 160-spiritbomb.height-GOKU_HEIGHT) {
                      spiritbomb.row = 160-spiritbomb.height-GOKU_HEIGHT;
                      rd = -rd;
                    }

                    drawImageDMA(spiritbomb.row,spiritbomb.col ,spiritbomb.width, spiritbomb.height, spiritbomb.image);
                    delay(1);
                    break;
            case DIALOGUE_END_1:
            waitForVBlank();
            drawRectDMA(myBuu.row, myBuu.col, myBuu.width, myBuu.height, BLACK);
            drawImageDMA(myBuu.row, myBuu.col, myBuu.width, myBuu.height, myBuu.image);


            drawString(myGoku.row,myGoku.col + 50,"Maybe you'll come back", WHITE);
            drawString(myGoku.row + 20,myGoku.col + 50,"someday,", WHITE);
            drawString(myGoku.row + 40,myGoku.col + 50,"as a better person", WHITE);
            state = DIALOGUE_END_2;

            case DIALOGUE_END_2:
            waitForVBlank();
            drawImageDMA(myBuu.row+2, myBuu.col+2, spiritbomb.width, spiritbomb.height, spiritbomb.image);

            if (KEY_DOWN(BUTTON_UP, BUTTONS)) {
                state = END_1;
            }
            break;

            case END_1:
                waitForVBlank();
                drawFullScreenImageDMA(gameover);
                state = END_2;
                break;
            case END_2:
                waitForVBlank();
                drawString(140, 70, "THANKS FOR YOUR HELP!", WHITE);
                drawString(150, 70, "PRESS SELECT TO GO AGAIN", WHITE);
                if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                  state = START;
                }
                break;
                // state = ?

        }
        previousButtons = currentButtons; // Store the current state of the buttons
    }
    return 0;
}



void delay(int n) {
  volatile int x = 0;
  for (int i = 0; i < n * 8000; i++)
  {
    x++;
    }
  }



// void redrawScore() {
//   int a = 0;
// }



